name: lie_detection_web
description: USJP Final Year Research WEB Application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_neumorphic: ^3.2.0
  flutter_svg: ^1.1.0
  chewie: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/SvgIcons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf